# -*- coding: utf-8 -*-
"""Copy of MASTER SWING TRADING SYSTEM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4s30hdM3qFcCrRS4Xku6OA0dVv8g8CB
"""

pip install pandas yfinance ta requests

!pip install yfinance ta pandas numpy feedparser transformers torch

# ============================================
# MASTER TRADING SYSTEM
# ============================================

import pandas as pd, yfinance as yf, ta, numpy as np
import concurrent.futures, warnings, logging, feedparser
from transformers import pipeline

warnings.simplefilter("ignore")
logging.getLogger("yfinance").setLevel(logging.CRITICAL)

sentiment_model = pipeline("sentiment-analysis")

# ============================================
# LOAD STOCK UNIVERSE
# ============================================

def get_symbols():
    df=pd.read_csv("https://archives.nseindia.com/content/indices/ind_nifty200list.csv")
    return [s+".NS" for s in df["Symbol"]]

symbols=get_symbols()

print("Scanning",len(symbols),"stocks...\n")

# ============================================
# NEWS SENTIMENT
# ============================================

def news_sentiment():
    url="https://news.google.com/rss/search?q=indian+stock+market&hl=en-IN&gl=IN&ceid=IN:en"
    feed=feedparser.parse(url)

    scores=[]
    for entry in feed.entries[:10]:
        r=sentiment_model(entry.title)[0]
        score=r["score"] if r["label"]=="POSITIVE" else -r["score"]
        scores.append(score)

    return np.mean(scores) if scores else 0


# ============================================
# MARKET SENTIMENT
# ============================================

def market_sentiment():

    import yfinance as yf

    # ---------- NIFTY TREND ----------
    nifty = yf.download("^NSEI", period="3mo", progress=False)

    if nifty.empty:
        return "NEUTRAL", 0

    ema20 = nifty["Close"].ewm(span=20).mean().iloc[-1]
    ema50 = nifty["Close"].ewm(span=50).mean().iloc[-1]

    trend = 1 if float(ema20) > float(ema50) else -1


    # ---------- VIX ----------
    vix = yf.download("^INDIAVIX", period="5d", progress=False)

    if vix.empty:
        vol = 0
    else:
        v = float(vix["Close"].iloc[-1])

        if v < 15:
            vol = 1
        elif v > 20:
            vol = -1
        else:
            vol = 0


    # ---------- NEWS SENTIMENT ----------
    try:
        news = float(news_sentiment())
    except:
        news = 0


    # ---------- FINAL SCORE ----------
    score = trend + vol + news


    # ---------- INTERPRETATION ----------
    if score > 1:
        mood = "BULLISH"
    elif score < -1:
        mood = "BEARISH"
    else:
        mood = "NEUTRAL"

    return mood, round(score,2)



# ============================================
# STRATEGY DETECTOR
# ============================================

def analyze(symbol):

    try:
        df = yf.download(symbol, period="6mo", interval="1d", progress=False, auto_adjust=True)

        if df.empty or len(df)<60:
            return None

        df["ema20"]=ta.trend.ema_indicator(df.Close,20)
        df["ema50"]=ta.trend.ema_indicator(df.Close,50)
        df["rsi"]=ta.momentum.rsi(df.Close,14)
        df["atr"]=ta.volatility.average_true_range(df.High,df.Low,df.Close,14)

        last=df.iloc[-1]

        strategies=[]
        score=0

        # TREND PULLBACK
        if last.ema20>last.ema50 and last.Close<last.ema20*1.03:
            strategies.append("Pullback Trend")
            score+=2

        # BREAKOUT
        high20=df.High.rolling(20).max().iloc[-2]
        if last.Close>high20:
            strategies.append("Breakout Momentum")
            score+=3

        # VOLATILITY EXPANSION
        if last.atr>df.atr.mean():
            strategies.append("Volatility Expansion")
            score+=1

        # MEAN REVERSION
        if last.rsi<30:
            strategies.append("Mean Reversion")
            score+=2

        if score<2:
            return None

        entry=round(last.Close,2)
        sl=round(entry-last.atr,2)
        target=round(entry+2*last.atr,2)

        return (symbol,entry,sl,target,score,", ".join(strategies))

    except:
        return None


# ============================================
# SCAN MARKET
# ============================================

results=[]

with concurrent.futures.ThreadPoolExecutor(10) as ex:
    for r in ex.map(analyze,symbols):
        if r: results.append(r)


# ============================================
# OUTPUT
# ============================================

mood,score=market_sentiment()

print("\nMarket Mood:",mood,"| Score:",score,"\n")

if not results:
    print("No high probability trades today.")
else:

    results=sorted(results,key=lambda x:x[4],reverse=True)

    for r in results:
        print(f"""
Stock: {r[0]}
Strategy: {r[5]}
Entry: {r[1]}
Stop Loss: {r[2]}
Target: {r[3]}
Strength Score: {r[4]}
""")

!pip install yfinance ta feedparser transformers torch torchvision \
             vectorbt requests pandas numpy scipy matplotlib seaborn \
             "python-telegram-bot>=20.0" schedule -q

!pip install "anyio>=4.5" "tornado>=6.2" -q

# IMPORTS & CONFIGURATION

import os, time, logging, warnings, functools, requests, smtplib
from io import StringIO
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import feedparser
import ta
import torch
import yfinance as yf
import concurrent.futures
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

warnings.simplefilter("ignore")
logging.getLogger("yfinance").setLevel(logging.CRITICAL)
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ============================================================
# MASTER CONFIGURATION — Edit ONLY this block
# ============================================================

import requests
import logging

log = logging.getLogger(__name__)

CONFIG = {
    # ── Capital & Risk ────────────────────────────────────────
    "TOTAL_CAPITAL":        2500000,
    "RISK_PER_TRADE_PCT":   0.01,
    "MAX_OPEN_TRADES":      10,
    "MAX_SECTOR_EXPOSURE":  0.30,

    # ── Universe ──────────────────────────────────────────────
    # Valid options: "nifty50", "niftynext50", "nifty100",
    # "nifty200", "nifty500", "niftymidcap50", "niftymidcap100"
    "UNIVERSE":             ["nifty200", "nifty500"],

    # ── Signal Thresholds ─────────────────────────────────────
    "MIN_SCORE":            6,
    "MIN_RR":               2.0,
    "MIN_ADX":              22,
    "MIN_VOLUME":           500000,
    "MIN_SENTIMENT":        -0.1,

    # ── Timeframes ────────────────────────────────────────────
    "PRIMARY_TF":           "1d",
    "CONFIRM_TF":           "1wk",
    "ENTRY_TF":             "1h",

    # ── Sentiment ─────────────────────────────────────────────
    "SENTIMENT_SOURCES":    5,
    "SENTIMENT_WEIGHT":     1.5,

    # ── Regime Detection ──────────────────────────────────────
    "REGIME_SYMBOL":        "^NSEI",
    "REGIME_PERIOD":        "6mo",

    # ── Alerts ────────────────────────────────────────────────
    "TELEGRAM_BOT_TOKEN":   "",
    "TELEGRAM_CHAT_ID":     "995467156",
    "EMAIL_SENDER":         "",
    "EMAIL_PASSWORD":       "",
    "EMAIL_RECEIVER":       "",

    # ── Google Drive ──────────────────────────────────────────
    "SAVE_TO_DRIVE":        False,
    "DRIVE_OUTPUT_PATH":    "/content/drive/MyDrive/SwingTrading/",
    "DRIVE_FOLDER":         "SwingTradingReports",

    # ── Backtest ──────────────────────────────────────────────
    "BACKTEST_PERIOD":      "3y",
    "BACKTEST_FEES":        0.001,
    "BT_START": "2022-01-01",   # 3 years back
    "BT_END":   "2026-02-01",   # up to end of last year
}

print("✅ CONFIG loaded successfully!")
print(f"   Capital      : ₹{CONFIG['TOTAL_CAPITAL']:,}")
print(f"   Risk/Trade   : {CONFIG['RISK_PER_TRADE_PCT']*100:.1f}%  →  ₹{CONFIG['TOTAL_CAPITAL']*CONFIG['RISK_PER_TRADE_PCT']:,.0f} per trade")
print(f"   Max Positions: {CONFIG['MAX_OPEN_TRADES']}")
print(f"   Universe     : {CONFIG['UNIVERSE']}")
print(f"   Min Score    : {CONFIG['MIN_SCORE']}/10  |  Min R:R: {CONFIG['MIN_RR']}  |  Min ADX: {CONFIG['MIN_ADX']}")

# TELEGRAM & EMAIL ALERTS
def send_telegram(message: str) -> bool:
    """Send a message via Telegram Bot."""
    token = CONFIG["TELEGRAM_BOT_TOKEN"]
    chat_id = CONFIG["TELEGRAM_CHAT_ID"]
    if not token or not chat_id:
        log.warning("Telegram not configured. Skipping.")
        return False
    try:
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        payload = {"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}
        r = requests.post(url, json=payload, timeout=10)
        return r.status_code == 200
    except Exception as e:
        log.error(f"Telegram send failed: {e}")
        return False


def send_email(subject: str, body: str) -> bool:
    """Send trade alert via Gmail."""
    sender   = CONFIG["EMAIL_SENDER"]
    password = CONFIG["EMAIL_PASSWORD"]
    receiver = CONFIG["EMAIL_RECEIVER"]
    if not all([sender, password, receiver]):
        log.warning("Email not configured. Skipping.")
        return False
    try:
        msg = MIMEMultipart()
        msg["From"]    = sender
        msg["To"]      = receiver
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "html"))
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, receiver, msg.as_string())
        return True
    except Exception as e:
        log.error(f"Email send failed: {e}")
        return False


def format_alert(trade: dict) -> tuple:
    """Format a trade signal for Telegram + Email."""
    tg = (
        f"🚨 *SWING TRADE ALERT*\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"📌 *{trade['symbol']}*\n"
        f"📊 Strategy : {trade['strategies']}\n"
        f"📈 Regime   : {trade['regime']}\n"
        f"💬 Sentiment: {trade['sentiment_label']} ({trade['sentiment_score']:+.2f})\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"🟢 Entry    : ₹{trade['entry']}\n"
        f"🔴 Stop Loss: ₹{trade['sl']}\n"
        f"🎯 Target 1 : ₹{trade['target1']}\n"
        f"🎯 Target 2 : ₹{trade['target2']}\n"
        f"⚖️  R:R      : {trade['rr']}\n"
        f"📦 Qty      : {trade['qty']} shares\n"
        f"💰 Capital  : ₹{trade['capital_deployed']:,.0f}\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"⭐ Score    : {trade['score']}/10\n"
        f"🕐 {datetime.now().strftime('%d %b %Y %H:%M')}"
    )
    html = (
        f"<html><body style='font-family:Arial;'>"
        f"<h2 style='color:#d32f2f;'>🚨 Swing Trade Alert</h2>"
        f"<table border='1' cellpadding='8' style='border-collapse:collapse;'>"
        f"<tr><td><b>Symbol</b></td><td>{trade['symbol']}</td></tr>"
        f"<tr><td><b>Strategy</b></td><td>{trade['strategies']}</td></tr>"
        f"<tr><td><b>Entry</b></td><td>₹{trade['entry']}</td></tr>"
        f"<tr><td><b>Stop Loss</b></td><td>₹{trade['sl']}</td></tr>"
        f"<tr><td><b>Target 1</b></td><td>₹{trade['target1']}</td></tr>"
        f"<tr><td><b>Target 2</b></td><td>₹{trade['target2']}</td></tr>"
        f"<tr><td><b>R:R</b></td><td>{trade['rr']}</td></tr>"
        f"<tr><td><b>Qty</b></td><td>{trade['qty']} shares</td></tr>"
        f"<tr><td><b>Capital</b></td><td>₹{trade['capital_deployed']:,.0f}</td></tr>"
        f"<tr><td><b>Score</b></td><td>{trade['score']}/10</td></tr>"
        f"<tr><td><b>Sentiment</b></td><td>{trade['sentiment_label']} ({trade['sentiment_score']:+.2f})</td></tr>"
        f"<tr><td><b>Regime</b></td><td>{trade['regime']}</td></tr>"
        f"</table>"
        f"<p style='color:gray;font-size:11px;'>Generated: {datetime.now().strftime('%d %b %Y %H:%M')}</p>"
        f"</body></html>"
    )
    return tg, html

def dispatch_alerts(trades: list):
    """Send all trade alerts via Telegram and Email."""
    if not trades:
        send_telegram("✅ Scan complete. No high-probability setups today.")
        return

    summary = f"📋 *Scan Complete* — {len(trades)} signal(s) found\n\n"
    for t in trades:
        summary += f"• *{t['symbol']}* | ₹{t['entry']} | Score {t['score']} | {t['strategies']}\n"
    send_telegram(summary)

    for trade in trades:
        result = format_alert(trade)
        if not result:
            print("Skipped trade:", trade["symbol"])
            continue

        tg_msg, html_body = result
        send_telegram(tg_msg)
        send_email(
            subject=f"[SwingAlert] {trade['symbol']} — {trade['strategies']}",
            body=html_body
        )
        time.sleep(0.5)

# ===========================================================================
# STOCK UNIVERSE LOADER
# ===========================================================================

from io import StringIO

UNIVERSE_URLS = {
    "nifty50":          "https://archives.nseindia.com/content/indices/ind_nifty50list.csv",
    "niftynext50":      "https://archives.nseindia.com/content/indices/ind_niftynext50list.csv",
    "nifty100":         "https://archives.nseindia.com/content/indices/ind_nifty100list.csv",
    "nifty200":         "https://archives.nseindia.com/content/indices/ind_nifty200list.csv",
    "nifty500":         "https://archives.nseindia.com/content/indices/ind_nifty500list.csv",
    "niftymidcap50":    "https://archives.nseindia.com/content/indices/ind_niftymidcap50list.csv",
    "niftymidcap100":   "https://archives.nseindia.com/content/indices/ind_niftymidcap100list.csv",
    "niftysmallcap50":  "https://archives.nseindia.com/content/indices/ind_niftysmallcap50list.csv",
    "niftysmalcap100":  "https://archives.nseindia.com/content/indices/ind_niftysmallcap100list.csv",
}

_symbol_cache = {}

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

def get_symbols(universes: list = None) -> list:
    """
    Load and deduplicate NSE symbols from selected indices.
    Falls back to a hardcoded Nifty 50 list if all downloads fail.
    """
    global _symbol_cache

    # Normalize to lowercase
    universes = [u.lower() for u in (universes or CONFIG["UNIVERSE"])]
    cache_key = tuple(sorted(universes))

    if cache_key in _symbol_cache:
        print(f"  📦 Returning cached symbols: {len(_symbol_cache[cache_key])} symbols")
        return _symbol_cache[cache_key]

    all_symbols = set()

    for u in universes:
        url = UNIVERSE_URLS.get(u)
        if not url:
            print(f"  ⚠️  Unknown universe '{u}'. Valid: {list(UNIVERSE_URLS.keys())}")
            continue

        try:
            r = requests.get(url, headers=HEADERS, timeout=15)
            r.raise_for_status()
            df = pd.read_csv(StringIO(r.text))

            # Find symbol column
            col = next((c for c in df.columns if "symbol" in c.lower()), df.columns[0])
            syms = [s.strip() + ".NS" for s in df[col].dropna() if isinstance(s, str)]

            all_symbols.update(syms)
            print(f"  ✅ {u}: {len(syms)} symbols loaded")
            log.info(f"Loaded {len(syms)} symbols from {u}")

        except requests.exceptions.HTTPError as e:
            print(f"  ❌ {u}: HTTP error — {e}")
            log.error(f"HTTP error loading {u}: {e}")
        except requests.exceptions.Timeout:
            print(f"  ❌ {u}: Request timed out")
            log.error(f"Timeout loading {u}")
        except Exception as e:
            print(f"  ❌ {u}: Failed — {e}")
            log.error(f"Failed to load {u}: {e}")

    # ── Fallback if nothing loaded ─────────────────────────────────────────
    if not all_symbols:
        print("\n  ⚠️  All downloads failed. Using hardcoded Nifty 50 fallback list.")
        log.warning("Using hardcoded fallback symbol list.")
        all_symbols = {
            "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
            "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
            "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "TITAN.NS",
            "SUNPHARMA.NS", "BAJFINANCE.NS", "WIPRO.NS", "ULTRACEMCO.NS", "NESTLEIND.NS",
            "POWERGRID.NS", "NTPC.NS", "TECHM.NS", "HCLTECH.NS", "ONGC.NS",
            "BAJAJFINSV.NS", "TATAMOTORS.NS", "ADANIENT.NS", "JSWSTEEL.NS", "TATASTEEL.NS",
        }

    result = sorted(list(all_symbols))
    _symbol_cache[cache_key] = result
    print(f"\n  📦 Total unique symbols: {len(result)}")
    log.info(f"Total unique symbols: {len(result)}")
    return result


def test_universe_loader():
    """Quick test to verify symbol loading works."""
    print("Testing Universe Loader...\n")
    global _symbol_cache
    _symbol_cache = {}  # Clear cache for fresh test
    symbols = get_symbols(["nifty50"])
    print(f"\nFirst 5 symbols: {symbols[:5]}")
    print(f"Last  5 symbols: {symbols[-5:]}")
    print("\n✅ Universe loader working!" if symbols else "\n❌ No symbols loaded!")

test_universe_loader()

# FINBERT SENTIMENT ENGINE

_finbert_model  = None
_finbert_tokenizer = None

# Add a threading lock around FinBERT inference in finbert_score()
import threading
_finbert_lock = threading.Lock()

def finbert_score(texts: list) -> float:
    if not texts:
        return 0.0
    model, tokenizer = load_finbert()
    scores = []
    with _finbert_lock:  # ← prevents concurrent GPU/CPU inference
        for i in range(0, len(texts), 8):
            batch = texts[i:i+8]
            inputs = tokenizer(batch, return_tensors="pt", truncation=True,
                               padding=True, max_length=128)
            with torch.no_grad():
                outputs = model(**inputs)
                probs = torch.softmax(outputs.logits, dim=-1).cpu().numpy()
            for p in probs:
                scores.append(float(p[0]) - float(p[1]))
    return float(np.mean(scores))

def load_finbert():
    """Lazy-load ProsusAI/finbert — finance-specific sentiment model."""
    global _finbert_model, _finbert_tokenizer
    if _finbert_model is None:
        log.info("Loading FinBERT model (first run only)...")
        model_name = "ProsusAI/finbert"
        _finbert_tokenizer = AutoTokenizer.from_pretrained(model_name)
        _finbert_model     = AutoModelForSequenceClassification.from_pretrained(model_name)
        _finbert_model.eval()
        if torch.cuda.is_available():
            _finbert_model = _finbert_model.cuda()
            log.info("FinBERT running on GPU ✓")
        else:
            log.info("FinBERT running on CPU")
    return _finbert_model, _finbert_tokenizer


def finbert_score(texts: list) -> float:
    """
    Score a list of financial headlines using FinBERT.
    Returns a float in [-1, +1]:
      +1 = strongly positive, -1 = strongly negative.
    FinBERT output labels: positive / negative / neutral
    """
    if not texts:
        return 0.0

    model, tokenizer = load_finbert()
    scores = []

    # Batch in groups of 8 to avoid OOM
    batch_size = 8
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        inputs = tokenizer(
            batch, return_tensors="pt", truncation=True,
            padding=True, max_length=128
        )
        if torch.cuda.is_available():
            inputs = {k: v.cuda() for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)
            probs   = torch.softmax(outputs.logits, dim=-1).cpu().numpy()

        # FinBERT label order: positive=0, negative=1, neutral=2
        for p in probs:
            score = float(p[0]) - float(p[1])  # positive - negative
            scores.append(score)

    return float(np.mean(scores))

# ── TTL Cache ─────────────────────────────────────────────────────────────

def ttl_cache(seconds: int = 600):
    def decorator(fn):
        cache = {}
        @functools.wraps(fn)
        def wrapper(*args):
            now = time.time()
            if args in cache and now - cache[args][1] < seconds:
                return cache[args][0]
            result = fn(*args)
            cache[args] = (result, now)
            return result
        return wrapper
    return decorator


NEWS_FEEDS = {
    "market": [
        "https://news.google.com/rss/search?q=indian+stock+market&hl=en-IN&gl=IN&ceid=IN:en",
        "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
        "https://www.moneycontrol.com/rss/marketreports.xml",
    ],
    "stock_template": "https://news.google.com/rss/search?q={query}+NSE+stock&hl=en-IN&gl=IN&ceid=IN:en",
}


@ttl_cache(seconds=1800)
def market_news_sentiment() -> float:
    """Aggregate FinBERT sentiment from multiple market news feeds."""
    titles = []
    for url in NEWS_FEEDS["market"]:
        try:
            feed = feedparser.parse(url)
            titles += [e.title for e in feed.entries[:5]]
        except:
            pass
    if not titles:
        return 0.0
    score = finbert_score(titles[:20])
    log.info(f"Market news sentiment: {score:+.3f}")
    return score


@ttl_cache(seconds=3600)
def stock_news_sentiment(symbol: str) -> tuple:
    """
    Get FinBERT sentiment for a specific stock.
    Returns (score: float, label: str)
    """
    query = symbol.replace(".NS", "").replace("-", " ")
    url   = NEWS_FEEDS["stock_template"].format(query=query)
    try:
        feed   = feedparser.parse(url)
        titles = [e.title for e in feed.entries[:CONFIG["SENTIMENT_SOURCES"]]]
        if not titles:
            return 0.0, "NEUTRAL"
        score = finbert_score(titles)
        label = "POSITIVE" if score > 0.1 else ("NEGATIVE" if score < -0.1 else "NEUTRAL")
        return round(score, 4), label
    except Exception as e:
        log.warning(f"Stock sentiment failed for {symbol}: {e}")
        return 0.0, "NEUTRAL"

# ===========================================================================
# MARKET REGIME DETECTOR
# ===========================================================================

@ttl_cache(seconds=600)
def detect_market_regime() -> dict:
    """
    Classify the market into one of five regimes using:
    - NIFTY 50 EMA trend (20/50/200)
    - ADX for trend strength
    - India VIX (dynamic percentile thresholds)
    - FinBERT market sentiment
    """

    fallback = {
        "regime":      "RANGING",
        "composite":   0.0,
        "adx":         0.0,
        "trend_score": 2,
        "vix":         15.0,
        "vix_p25":     12.0,
        "vix_p75":     18.0,
        "news_score":  0.0,
        "ema20":       0.0,
        "ema50":       0.0,
        "ema200":      0.0,
    }

    try:
        # ── Download NIFTY + VIX separately (avoids MultiIndex issues) ────
        nifty = yf.download("^NSEI",     period="1y", progress=False, auto_adjust=True)
        vix   = yf.download("^INDIAVIX", period="1y", progress=False, auto_adjust=True)

        if nifty.empty:
            log.warning("No NIFTY data returned from yfinance. Using fallback.")
            return fallback

        # ── Flatten MultiIndex if present ─────────────────────────────────
        if isinstance(nifty.columns, pd.MultiIndex):
            nifty.columns = nifty.columns.get_level_values(0)
        if isinstance(vix.columns, pd.MultiIndex):
            vix.columns = vix.columns.get_level_values(0)

        # ── NIFTY Close ───────────────────────────────────────────────────
        nifty_close = nifty["Close"].dropna()
        if len(nifty_close) < 200:
            log.warning("Insufficient NIFTY data. Using fallback.")
            return fallback

        ema20  = float(nifty_close.ewm(span=20).mean().iloc[-1])
        ema50  = float(nifty_close.ewm(span=50).mean().iloc[-1])
        ema200 = float(nifty_close.ewm(span=200).mean().iloc[-1])
        price  = float(nifty_close.iloc[-1])

        trend_score = sum([
            price  > ema20,
            ema20  > ema50,
            ema50  > ema200,
            price  > ema200,
        ])  # 0–4

        # ── ADX ───────────────────────────────────────────────────────────
        nifty_full = nifty[["High", "Low", "Close"]].dropna()
        if len(nifty_full) < 20:
            log.warning("Insufficient NIFTY OHLC data for ADX. Using fallback.")
            return fallback

        adx_ind    = ta.trend.ADXIndicator(
            nifty_full["High"], nifty_full["Low"], nifty_full["Close"], window=14
        )
        adx_series = adx_ind.adx().dropna()
        adx_val    = float(adx_series.iloc[-1]) if not adx_series.empty else 0.0

        # ── VIX ───────────────────────────────────────────────────────────
        vix_series = vix["Close"].dropna() if not vix.empty else pd.Series(dtype=float)
        if vix_series.empty:
            log.warning("VIX data missing. Defaulting VIX values.")
            vix_now, vix_p25, vix_p75, vix_score = 15.0, 12.0, 18.0, 0
        else:
            vix_now  = float(vix_series.iloc[-1])
            vix_p25  = float(np.percentile(vix_series, 25))
            vix_p75  = float(np.percentile(vix_series, 75))
            if vix_now < vix_p25:
                vix_score = 1     # Low fear → bullish
            elif vix_now > vix_p75:
                vix_score = -1    # High fear → bearish
            else:
                vix_score = 0

        # ── Sentiment ─────────────────────────────────────────────────────
        try:
            news_score = market_news_sentiment()
            if not isinstance(news_score, (int, float)):
                news_score = 0.0
        except Exception as se:
            log.warning(f"Sentiment fetch failed: {se}. Defaulting to 0.")
            news_score = 0.0

        # ── Composite Score & Regime ───────────────────────────────────────
        composite = (trend_score - 2) + vix_score + (news_score * 2)

        if adx_val > CONFIG["MIN_ADX"]:
            if composite >= 1.5:
                regime = "STRONG_BULL"
            elif composite <= -1.5:
                regime = "STRONG_BEAR"
            elif composite > 0:
                regime = "MILD_BULL"
            else:
                regime = "MILD_BEAR"
        else:
            regime = "RANGING"

        result = {
            "regime":      regime,
            "composite":   round(composite, 2),
            "adx":         round(adx_val, 2),
            "trend_score": trend_score,
            "vix":         round(vix_now, 2),
            "vix_p25":     round(vix_p25, 2),
            "vix_p75":     round(vix_p75, 2),
            "news_score":  round(news_score, 3),
            "ema20":       round(ema20, 2),
            "ema50":       round(ema50, 2),
            "ema200":      round(ema200, 2),
        }

        log.info(
            f"Market Regime: {regime} | ADX: {adx_val:.1f} | "
            f"VIX: {vix_now:.1f} | Composite: {composite:.2f}"
        )
        return result

    except Exception as e:
        import traceback
        log.error(f"Regime detection failed: {e}")
        traceback.print_exc()
        return fallback


# ===========================================================================
# REGIME-SPECIFIC STRATEGY WEIGHTS
# ===========================================================================
REGIME_WEIGHTS = {
    "STRONG_BULL": {"Breakout": 3.0, "Pullback": 2.5, "MeanReversion": 0.5, "Divergence": 1.5},
    "MILD_BULL":   {"Breakout": 2.5, "Pullback": 2.0, "MeanReversion": 1.0, "Divergence": 2.0},
    "RANGING":     {"Breakout": 1.0, "Pullback": 1.0, "MeanReversion": 3.0, "Divergence": 2.5},
    "MILD_BEAR":   {"Breakout": 0.5, "Pullback": 0.5, "MeanReversion": 2.0, "Divergence": 1.5},
    "STRONG_BEAR": {"Breakout": 0.0, "Pullback": 0.0, "MeanReversion": 1.5, "Divergence": 1.0},
}

# ── Test Market Regime Detector ───────────────────────────────────────────
print("Testing detect_market_regime()...\n")

regime_data = detect_market_regime()

print(f"✅ Regime      : {regime_data['regime']}")
print(f"✅ ADX         : {regime_data['adx']}")
print(f"✅ Composite   : {regime_data['composite']}")
print(f"✅ Trend Score : {regime_data['trend_score']}")
print(f"✅ EMA20       : {regime_data['ema20']}")
print(f"✅ EMA50       : {regime_data['ema50']}")
print(f"✅ EMA200      : {regime_data['ema200']}")
print(f"✅ VIX         : {regime_data['vix']}")
print(f"✅ VIX P25     : {regime_data['vix_p25']}")
print(f"✅ VIX P75     : {regime_data['vix_p75']}")
print(f"✅ News Score  : {regime_data['news_score']}")

print("\n" + "="*40)
print("All keys present — Regime detector working!")

# ===========================================================================
# MULTI-TIMEFRAME ANALYSIS ENGINE
# ===========================================================================

def fetch_mtf_data(symbol: str) -> dict:
    tfs = {
        "daily":  ("6mo", "1d",  60),
        "weekly": ("2y",  "1wk", 52),
        "hourly": ("60d", "1h",  48),
    }
    result = {}
    ticker = yf.Ticker(symbol)  # ← use Ticker, not download

    for name, (period, interval, min_rows) in tfs.items():
        try:
            df = ticker.history(
                period=period,
                interval=interval,
                auto_adjust=True,    # split + dividend adjusted
                actions=False        # drop Dividends/Stock Splits columns
            )

            if df.empty:
                return {}

            # history() always returns flat columns — no MultiIndex issues
            df = df[["Open", "High", "Low", "Close", "Volume"]].copy()
            df = df.apply(pd.to_numeric, errors="coerce")
            df.dropna(subset=["Close", "High", "Low"], inplace=True)

            if len(df) < min_rows:
                return {}

            result[name] = df

        except Exception as e:
            log.warning(f"[{symbol}] {name} data fetch failed: {e}")
            return {}

    return result
    """
    Download Daily, Weekly, and Hourly OHLCV data for a symbol.
    Returns dict with keys: 'daily', 'weekly', 'hourly'
    """
    tfs = {
        "daily":  ("6mo", "1d",  60),
        "weekly": ("2y",  "1wk", 52),
        "hourly": ("60d", "1h",  48),
    }
    result = {}
    for name, (period, interval, min_rows) in tfs.items():
        try:
            df = yf.download(
                symbol, period=period, interval=interval,
                progress=False, auto_adjust=True
            )

            # Flatten MultiIndex columns
            # ✅ FIX: Always drop the ticker level correctly
            if isinstance(df.columns, pd.MultiIndex):
              df.columns = df.columns.get_level_values(0)  # Gets the Price field (Close, Open, etc.)

            # Drop duplicate columns
            df = df.loc[:, ~df.columns.duplicated()]

            # Keep only OHLCV
            df = df[["Open", "High", "Low", "Close", "Volume"]].copy()
            df = df.apply(pd.to_numeric, errors="coerce")
            df.dropna(subset=["Close", "High", "Low"], inplace=True)

            if len(df) < min_rows:
                return {}

            result[name] = df

        except Exception as e:
            log.warning(f"[{symbol}] {name} data fetch failed: {e}")
            return {}
    return result


def compute_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Add a full indicator suite to an OHLCV DataFrame."""
    c = df["Close"].squeeze().astype(float)
    h = df["High"].squeeze().astype(float)
    l = df["Low"].squeeze().astype(float)
    v = df["Volume"].squeeze().astype(float)

    # Trend
    df["ema20"]       = ta.trend.ema_indicator(c, 20)
    df["ema50"]       = ta.trend.ema_indicator(c, 50)
    df["ema200"]      = ta.trend.ema_indicator(c, 200) if len(df) >= 200 else np.nan
    df["supertrend"]  = ta.trend.stc(c)

    # ADX
    adx_ind           = ta.trend.ADXIndicator(h, l, c, 14)
    df["adx"]         = adx_ind.adx()
    df["adx_pos"]     = adx_ind.adx_pos()
    df["adx_neg"]     = adx_ind.adx_neg()

    # MACD
    macd_ind          = ta.trend.MACD(c)
    df["macd"]        = macd_ind.macd()
    df["macd_signal"] = macd_ind.macd_signal()
    df["macd_hist"]   = macd_ind.macd_diff()

    # Momentum
    df["rsi"]         = ta.momentum.rsi(c, 14)
    df["stoch_k"]     = ta.momentum.stoch(h, l, c, 14, 3)
    df["stoch_d"]     = ta.momentum.stoch_signal(h, l, c, 14, 3)
    df["roc"]         = ta.momentum.roc(c, 10)

    # Volatility
    df["atr"]         = ta.volatility.average_true_range(h, l, c, 14)
    bb                = ta.volatility.BollingerBands(c, 20, 2)
    df["bb_upper"]    = bb.bollinger_hband()
    df["bb_lower"]    = bb.bollinger_lband()
    df["bb_width"]    = bb.bollinger_wband()
    df["bb_pct"]      = bb.bollinger_pband()

    # Volume
    df["obv"]         = ta.volume.on_balance_volume(c, v)
    df["vol_ma20"]    = v.rolling(20).mean()
    df["vol_ratio"]   = v / df["vol_ma20"]

    return df


def weekly_trend_bias(weekly_df: pd.DataFrame) -> int:
    """Returns +1 (bullish), -1 (bearish), 0 (neutral) based on weekly chart."""
    w = weekly_df
    if len(w) < 52:
        return 0
    c      = w["Close"].squeeze().astype(float)
    ema20w = float(c.ewm(span=20).mean().iloc[-1])
    ema50w = float(c.ewm(span=50).mean().iloc[-1])
    price  = float(c.iloc[-1])
    rsi_w  = float(ta.momentum.rsi(c, 14).iloc[-1])

    bull = sum([price > ema20w, ema20w > ema50w, rsi_w > 50])
    bear = sum([price < ema20w, ema20w < ema50w, rsi_w < 50])

    if bull >= 2: return 1
    if bear >= 2: return -1
    return 0


def hourly_entry_confirmation(hourly_df: pd.DataFrame, direction: int) -> bool:
    """Confirm entry on hourly chart for better timing."""
    if hourly_df is None or len(hourly_df) < 24:
        return True
    h          = hourly_df.copy()
    c          = h["Close"].squeeze().astype(float)
    h["ema9"]  = c.ewm(span=9).mean()
    h["ema21"] = c.ewm(span=21).mean()
    last       = h.iloc[-1]
    prev       = h.iloc[-2]

    if direction == 1:
        return (
            float(last["ema9"])  > float(last["ema21"]) and
            float(last["Close"]) > float(prev["Close"])
        )
    return True

# FUNDAMENTAL PRE-FILTER
# ===========================================================================

@ttl_cache(seconds=86400)  # Cache for 24 hours
def fundamental_filter(symbol: str) -> tuple:
    """
    Quick fundamental health check using yfinance.info.
    Returns (passes: bool, reason: str)
    Filters out: high debt, negative ROE, low liquidity, high promoter pledge.
    """
    try:
        info = yf.Ticker(symbol).info

        # Market cap filter — skip micro caps (too illiquid for ₹25L)
        mkt_cap = info.get("marketCap", 0)
        if mkt_cap and mkt_cap < 1_000_000_000:  # < ₹100 Cr
            return False, "Market cap too small"

        # Debt / Equity
        de = info.get("debtToEquity")
        if de is not None and de > 200:
            return False, f"High D/E ratio: {de:.0f}"

        # Return on Equity
        roe = info.get("returnOnEquity")
        if roe is not None and roe < -0.05:
            return False, f"Negative ROE: {roe:.2%}"

        # Current Ratio (liquidity)
        cr = info.get("currentRatio")
        if cr is not None and cr < 0.8:
            return False, f"Low current ratio: {cr:.2f}"

        # Earnings growth (don't require positive but penalise big negatives)
        eg = info.get("earningsGrowth")
        if eg is not None and eg < -0.40:
            return False, f"Earnings declined sharply: {eg:.0%}"

        return True, "OK"

    except Exception as e:
        # If data unavailable, allow through (don't disqualify on missing data)
        return True, "Fundamental data unavailable — allowed through"

# SIGNAL SCORER & TRADE SETUP GENERATOR
# ===========================================================================

def score_signals(daily: pd.DataFrame, weekly_bias: int,
                  regime: str) -> dict:
    """
    Evaluate all strategy signals on the daily chart.
    Returns a dict with score, strategies list, and direction.
    Score is normalised to 0–10.
    """
    w   = REGIME_WEIGHTS.get(regime, REGIME_WEIGHTS["RANGING"])
    d   = daily
    last = d.iloc[-1]
    prev = d.iloc[-2]

    strategies = []
    raw_score  = 0.0
    direction  = 0  # +1 long, -1 short

    # ── 1. TREND PULLBACK ────────────────────────────────────────────────
    # Price in uptrend (EMA20 > EMA50) but pulled back to EMA20 zone
    if (float(last["ema20"]) > float(last["ema50"]) and
            float(last["Close"]) < float(last["ema20"]) * 1.04 and
            float(last["Close"]) > float(last["ema20"]) * 0.97 and
            float(last["rsi"]) > 40 and float(last["adx"]) > 20):
        strategies.append("Trend Pullback")
        raw_score += w["Pullback"]
        direction = 1

    # ── 2. BREAKOUT WITH VOLUME ──────────────────────────────────────────
    high20 = d["High"].rolling(20).max().iloc[-2]  # -2 to avoid lookahead
    bb_squeeze = float(last["bb_width"]) < float(d["bb_width"].quantile(0.25))

    if float(last["Close"]) > float(high20):
        if float(last["vol_ratio"]) > 1.5:  # Volume surge
            strategies.append("Volume Breakout")
            raw_score += w["Breakout"]
            direction = 1
        elif bb_squeeze:  # Breakout from Bollinger squeeze
            strategies.append("Squeeze Breakout")
            raw_score += w["Breakout"] * 0.75
            direction = 1
        else:
            strategies.append("Breakout (Unconfirmed)")
            raw_score += w["Breakout"] * 0.4
            direction = 1

    # ── 3. MACD CROSSOVER (histogram turning positive) ───────────────────
    if (float(prev["macd_hist"]) < 0 and
            float(last["macd_hist"]) > 0 and
            float(last["macd"]) < 0):  # Crossover below zero line = early
        strategies.append("MACD Crossover")
        raw_score += 1.5
        direction = 1

    # ── 4. MEAN REVERSION (oversold bounce) ──────────────────────────────
    if (float(last["rsi"]) < 32 and
            float(last["stoch_k"]) < 25 and
            float(last["Close"]) > float(last["bb_lower"])):
        strategies.append("Mean Reversion")
        raw_score += w["MeanReversion"]
        direction = 1

    # ── 5. BULLISH RSI DIVERGENCE ─────────────────────────────────────────
    # Price makes lower low, RSI makes higher low
    window = 10
    if len(d) >= window + 2:
        price_lows_now  = float(d["Low"].iloc[-1])
        price_lows_prev = float(d["Low"].iloc[-window])
        rsi_now  = float(d["rsi"].iloc[-1])
        rsi_prev = float(d["rsi"].iloc[-window])

        if (price_lows_now < price_lows_prev and
                rsi_now > rsi_prev and
                rsi_now < 50):
            strategies.append("RSI Divergence")
            raw_score += w["Divergence"]
            direction = 1

    # ── 6. OBV CONFIRMATION ───────────────────────────────────────────────
    obv_trend = float(d["obv"].iloc[-1]) > float(d["obv"].ewm(span=20).mean().iloc[-1])
    if obv_trend and direction == 1:
        strategies.append("OBV Confirmed")
        raw_score += 0.5

    # ── 7. WEEKLY ALIGNMENT BONUS / PENALTY ──────────────────────────────
    if weekly_bias == 1 and direction == 1:
        raw_score += 1.0   # Weekly trend confirms daily signal
    elif weekly_bias == -1 and direction == 1:
        raw_score -= 1.5   # Trading against weekly trend → reduce score

    # ── 8. ADX STRENGTH BONUS ─────────────────────────────────────────────
    adx_val = float(last["adx"])
    if adx_val > 30:
        raw_score += 0.5
    elif adx_val < 15:
        raw_score -= 0.5

    # ── Normalise to 0–10 ─────────────────────────────────────────────────
    norm_score = min(10.0, max(0.0, (raw_score / 7.0) * 10.0))

    return {
        "score":      round(norm_score, 2),
        "strategies": strategies,
        "direction":  direction,
        "adx":        round(adx_val, 2),
    }


def build_trade_setup(symbol: str, daily: pd.DataFrame,
                      signal: dict, regime: str,
                      sentiment_score: float,
                      sentiment_label: str) -> dict:
    """
    Given a signal, build a complete trade setup with:
    - Dynamic ATR-based SL
    - Dual targets (T1 = 1.5R, T2 = 3R)
    - Trailing stop reference
    - Position size
    """
    last   = daily.iloc[-1]
    entry  = round(float(last["Close"]), 2)
    atr    = round(float(last["atr"]), 2)

    # Regime-adjusted ATR multipliers
    sl_mult = {
        "STRONG_BULL": 1.2, "MILD_BULL": 1.3,
        "RANGING":     1.5, "MILD_BEAR": 1.0, "STRONG_BEAR": 0.8,
    }.get(regime, 1.3)

    tgt1_mult = 1.5  # Conservative target (1.5 × risk)
    tgt2_mult = 3.0  # Extended target (3 × risk)

    sl       = round(entry - atr * sl_mult, 2)
    target1  = round(entry + atr * sl_mult * tgt1_mult, 2)
    target2  = round(entry + atr * sl_mult * tgt2_mult, 2)
    risk     = entry - sl
    rr       = round((target1 - entry) / risk, 2) if risk > 0 else 0

    # Sentiment adjustment on score
    final_score = round(
        signal["score"] + sentiment_score * CONFIG["SENTIMENT_WEIGHT"], 2
    )
    final_score = min(10.0, max(0.0, final_score))

    # Position size
    qty, capital_deployed = position_size(entry, sl)

    return {
        "symbol":           symbol,
        "entry":            entry,
        "sl":               sl,
        "target1":          target1,
        "target2":          target2,
        "atr":              atr,
        "rr":               rr,
        "score":            final_score,
        "strategies":       ", ".join(signal["strategies"]),
        "regime":           regime,
        "adx":              signal["adx"],
        "sentiment_score":  round(sentiment_score, 3),
        "sentiment_label":  sentiment_label,
        "qty":              qty,
        "capital_deployed": capital_deployed,
        "trailing_stop":    round(entry - atr * 2, 2),
        "date":             datetime.now().strftime("%Y-%m-%d"),
    }

# POSITION SIZING ENGINE
# ===========================================================================

def position_size(entry: float, sl: float) -> tuple:
    """
    Fixed Fractional Position Sizing.
    Risk exactly RISK_PER_TRADE_PCT of TOTAL_CAPITAL per trade.
    Returns (qty: int, capital_deployed: float)
    """
    risk_amount    = CONFIG["TOTAL_CAPITAL"] * CONFIG["RISK_PER_TRADE_PCT"]
    risk_per_share = entry - sl

    if risk_per_share <= 0:
        return 0, 0

    qty            = int(risk_amount / risk_per_share)
    capital        = round(qty * entry, 2)

    # Cap at MAX_OPEN_TRADES fraction of total capital
    max_capital    = CONFIG["TOTAL_CAPITAL"] / CONFIG["MAX_OPEN_TRADES"]
    if capital > max_capital:
        qty        = int(max_capital / entry)
        capital    = round(qty * entry, 2)

    return qty, capital

# =============================================================================
# MASTER SWING MARKET SCANNER
# =============================================================================

import concurrent.futures
from datetime import datetime


# =============================================================================
# SYMBOL ANALYSIS PIPELINE
# =============================================================================

def analyze_symbol(symbol: str, regime_data: dict) -> dict | None:
    """
    Full analysis pipeline for a single symbol.
    """

    regime = regime_data.get("regime", "RANGING")

    # ─────────────────────────────────────────────────────────────────────
    # 1. Fundamental Filter
    # ─────────────────────────────────────────────────────────────────────
    passes, _ = fundamental_filter(symbol)
    if not passes:
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 2. Fetch Multi-Timeframe Data
    # ─────────────────────────────────────────────────────────────────────
    mtf = fetch_mtf_data(symbol)
    if not mtf:
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 3. Indicator Computation
    # ─────────────────────────────────────────────────────────────────────
    try:
        daily  = compute_indicators(mtf["daily"].copy())
        weekly = compute_indicators(mtf["weekly"].copy())
        hourly = mtf.get("hourly")
    except Exception as e:
        log.warning(f"[{symbol}] Indicator computation failed: {e}")
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 4. Weekly Trend Bias
    # ─────────────────────────────────────────────────────────────────────
    w_bias = weekly_trend_bias(weekly)

    if regime == "STRONG_BEAR" and w_bias == 1:
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 5. Signal Scoring
    # ─────────────────────────────────────────────────────────────────────
    signal = score_signals(daily, w_bias, regime)

    if not signal["strategies"]:
        return None

    if signal["score"] < CONFIG["MIN_SCORE"]:
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 6. Hourly Confirmation
    # ─────────────────────────────────────────────────────────────────────
    if not hourly_entry_confirmation(hourly, signal["direction"]):
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 7. Risk : Reward Check
    # ─────────────────────────────────────────────────────────────────────
    last  = daily.iloc[-1]
    entry = round(float(last["Close"]), 2)
    atr   = float(last["atr"])

    sl     = round(entry - atr * 1.3, 2)
    target = round(entry + atr * 2.6, 2)

    risk   = entry - sl
    reward = target - entry
    rr     = round(reward / risk, 2) if risk > 0 else 0

    if rr < CONFIG["MIN_RR"]:
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 8. FinBERT Sentiment
    # ─────────────────────────────────────────────────────────────────────
    sent_score, sent_label = stock_news_sentiment(symbol)

    if sent_score < -0.4 and "Mean Reversion" not in signal["strategies"]:
        return None

    # ─────────────────────────────────────────────────────────────────────
    # 9. Build Trade Setup
    # ─────────────────────────────────────────────────────────────────────
    return build_trade_setup(
        symbol=symbol,
        daily=daily,
        signal=signal,
        regime=regime,
        sent_score=sent_score,
        sent_label=sent_label,
    )


# =============================================================================
# TRADE BUILDER
# =============================================================================

def build_trade_setup(
    symbol: str,
    daily,
    signal: dict,
    regime: str,
    sent_score: float,
    sent_label: str,
) -> dict:

    last  = daily.iloc[-1]
    entry = round(float(last["Close"]), 2)
    atr   = float(last["atr"])

    sl = round(entry - atr * 1.3, 2)
    t1 = round(entry + atr * 2.0, 2)
    t2 = round(entry + atr * 3.5, 2)

    risk = entry - sl
    rr   = round((t1 - entry) / risk, 2) if risk > 0 else 0

    qty, capital = position_size(entry, sl)

    return {
        "symbol": symbol,
        "entry": entry,
        "sl": sl,
        "target1": t1,
        "target2": t2,
        "rr": rr,
        "qty": qty,
        "capital_deployed": capital,
        "score": signal["score"],
        "strategies": ", ".join(signal["strategies"]),
        "direction": signal["direction"],
        "regime": regime,
        "sentiment_score": sent_score,
        "sentiment_label": sent_label,
        "timestamp": datetime.now().isoformat(),
    }


# =============================================================================
# FULL UNIVERSE SCANNER
# =============================================================================

def run_scan(top_n: int = 20) -> list:

    symbols     = get_symbols()
    regime_data = detect_market_regime()
    regime      = regime_data["regime"]

    print("\n" + "=" * 60)
    print(f"  MASTER SWING SCANNER — {datetime.now():%d %b %Y %H:%M}")
    print("=" * 60)
    print(f"  Regime  : {regime} | ADX: {regime_data['adx']}")
    print(f"  NIFTY   : EMA20={regime_data['ema20']} | EMA50={regime_data['ema50']}")
    print(f"  VIX     : {regime_data['vix']} "
          f"(P25={regime_data['vix_p25']} P75={regime_data['vix_p75']})")
    print(f"  News    : {regime_data['news_score']:+.3f}")
    print(f"  Universe: {len(symbols)} stocks")
    print("=" * 60 + "\n")

    if regime == "STRONG_BEAR":
        print("⚠ STRONG BEAR market detected. Strict filtering enabled.\n")

    results = []
    scanned = 0

    with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:

        futures = {
            executor.submit(analyze_symbol, s, regime_data): s
            for s in symbols
        }

        for future in concurrent.futures.as_completed(futures):

            symbol = futures[future]
            scanned += 1

            if scanned % 50 == 0:
                print(f"  Scanned {scanned}/{len(symbols)}...")

            try:
                result = future.result(timeout=60)
                if result:
                    results.append(result)
            except Exception as e:
                log.warning(f"[{symbol}] Thread failure: {e}")

    # Sort by score then RR
    results.sort(key=lambda x: (x["score"], x["rr"]), reverse=True)
    top = results[:top_n]

    print("\n" + "=" * 60)
    print(f"  ✅ Scan Complete | {len(results)} signals found")
    print(f"  Showing Top {len(top)}")
    print("=" * 60 + "\n")

    for t in top:
        print(
            f"{t['symbol']:<15} | "
            f"Score: {t['score']:>4.1f}/10 | "
            f"Entry: ₹{t['entry']:>8.2f} | "
            f"SL: ₹{t['sl']:>8.2f} | "
            f"T1: ₹{t['target1']:>8.2f} | "
            f"R:R {t['rr']:>4.1f} | "
            f"Qty: {t['qty']:>4} | "
            f"{t['strategies']}"
        )

    return top

# BACKTESTING ENGINE (vectorbt)
# ===========================================================================

def run_backtest(symbol: str, strategy: str = "breakout",
                 period: str = None) -> dict | None:
    """
    Backtest a single symbol using vectorbt.
    Supported strategies: 'breakout', 'pullback', 'mean_reversion'
    Returns a stats dictionary.
    """
    try:
        import vectorbt as vbt
    except ImportError:
        log.error("vectorbt not installed. Run: pip install vectorbt")
        return None

    period = period or CONFIG["BACKTEST_PERIOD"]

    try:
        ticker = yf.Ticker(symbol)
        df = ticker.history(period=period, interval="1d", auto_adjust=True, actions=False)
        if len(df) < 200:
          return None

        df = compute_indicators(df.copy())
        close = df["Close"]

        # ── Generate entry/exit signals by strategy ───────────────────────
        if strategy == "breakout":
          high20 = df["High"].rolling(20).max().shift(1)
          entries = (close > high20) & (df["vol_ratio"] > 1.5) & (df["adx"] > 20)
          exits   = (close < df["ema20"]) | (df["rsi"] > 75)

        elif strategy == "pullback":
            entries = (
                (df["ema20"] > df["ema50"]) &
                (close < df["ema20"] * 1.04) &
                (close > df["ema20"] * 0.97) &
                (df["rsi"] > 40) & (df["rsi"] < 65)
            )
            exits   = (close > df["ema20"] * 1.10) | (close < df["ema50"])

        elif strategy == "mean_reversion":
            entries = (df["rsi"] < 32) & (df["stoch_k"] < 25)
            exits   = (df["rsi"] > 60) | (df["stoch_k"] > 75)

        else:
            return None

        # ── Run vectorbt portfolio ─────────────────────────────────────────
        portfolio = vbt.Portfolio.from_signals(
            close,
            entries   = entries,
            exits     = exits,
            init_cash = CONFIG["TOTAL_CAPITAL"],
            fees      = CONFIG["BACKTEST_FEES"],
            sl_stop   = 0.05,  # 5% hard stop as safety net
            tp_stop   = 0.15,  # 15% hard take profit
        )

        stats = portfolio.stats()
        return {
            "symbol":        symbol,
            "strategy":      strategy,
            "total_return":  round(float(stats["Total Return [%]"]), 2),
            "sharpe":        round(float(stats.get("Sharpe Ratio", 0) or 0), 3),
            "max_dd":        round(float(stats["Max Drawdown [%]"]), 2),
            "win_rate":      round(float(stats["Win Rate [%]"]), 2),
            "total_trades":  int(stats["Total Trades"]),
            "avg_trade_pct": round(float(stats.get("Avg Winning Trade [%]", 0) or 0), 2),
            "portfolio":     portfolio,  # Full object for further analysis
        }

    except Exception as e:
        log.warning(f"[{symbol}] Backtest failed: {e}")
        return None


def backtest_universe(symbols: list = None, strategy: str = "breakout",
                      max_symbols: int = 50) -> pd.DataFrame:
    """
    Backtest a strategy across multiple symbols.
    Returns a DataFrame of results sorted by Sharpe ratio.
    """
    symbols = symbols or get_symbols()[:max_symbols]
    log.info(f"Backtesting {len(symbols)} symbols with '{strategy}' strategy...")

    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as ex:
        futures = {ex.submit(run_backtest, s, strategy): s for s in symbols}
        for i, future in enumerate(concurrent.futures.as_completed(futures)):
            if (i + 1) % 10 == 0:
                print(f"  Backtest progress: {i+1}/{len(symbols)}")
            try:
                r = future.result(timeout=120)
                if r:
                    results.append({k: v for k, v in r.items() if k != "portfolio"})
            except Exception as e:
                log.warning(f"Backtest thread error: {e}")

    if not results:
        print("No backtest results.")
        return pd.DataFrame()

    df = pd.DataFrame(results)
    df = df.sort_values("sharpe", ascending=False).reset_index(drop=True)

    print(f"\n{'='*70}")
    print(f"  BACKTEST RESULTS — Strategy: {strategy.upper()}")
    print(f"{'='*70}")
    print(df[["symbol","total_return","sharpe","max_dd",
              "win_rate","total_trades"]].to_string(index=False))

    return df

# RESULTS DASHBOARD & EXPORT
# ===========================================================================

def plot_dashboard(trades: list, regime_data: dict):
    """Generate a visual dashboard of today's scan results."""
    if not trades:
        print("No trades to visualise.")
        return

    df = pd.DataFrame(trades)

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle(
        f"Master Swing Scanner Dashboard — {datetime.now().strftime('%d %b %Y')}",
        fontsize=16, fontweight="bold"
    )

    # ── 1. Score distribution ─────────────────────────────────────────────
    ax = axes[0, 0]
    ax.barh(df["symbol"].str.replace(".NS", "")[:15],
            df["score"][:15], color="steelblue")
    ax.set_xlabel("Signal Score (/10)")
    ax.set_title("Top Signals by Score")
    ax.axvline(CONFIG["MIN_SCORE"], color="red", linestyle="--", label="Threshold")
    ax.legend()

    # ── 2. R:R distribution ───────────────────────────────────────────────
    ax = axes[0, 1]
    ax.hist(df["rr"], bins=15, color="green", alpha=0.7, edgecolor="black")
    ax.set_xlabel("Risk:Reward Ratio")
    ax.set_title("R:R Distribution")
    ax.axvline(CONFIG["MIN_RR"], color="red", linestyle="--", label=f"Min R:R ({CONFIG['MIN_RR']})")
    ax.legend()

    # ── 3. Sentiment distribution ─────────────────────────────────────────
    ax = axes[0, 2]
    colors = ["green" if s > 0.1 else ("red" if s < -0.1 else "gray")
              for s in df["sentiment_score"]]
    ax.bar(df["symbol"].str.replace(".NS", "")[:15],
           df["sentiment_score"][:15], color=colors[:15])
    ax.set_ylabel("FinBERT Sentiment Score")
    ax.set_title("Stock-Level Sentiment")
    ax.axhline(0, color="black", linewidth=0.8)
    ax.tick_params(axis="x", rotation=45)

    # ── 4. Capital allocation ─────────────────────────────────────────────
    ax = axes[1, 0]
    top10 = df.head(10)
    ax.pie(
        top10["capital_deployed"],
        labels=top10["symbol"].str.replace(".NS", ""),
        autopct="%1.1f%%", startangle=90
    )
    ax.set_title("Capital Allocation (Top 10)")

    # ── 5. Market Regime Gauge ────────────────────────────────────────────
    ax = axes[1, 1]
    regime_colors = {
        "STRONG_BULL": "darkgreen", "MILD_BULL": "limegreen",
        "RANGING": "orange", "MILD_BEAR": "tomato", "STRONG_BEAR": "darkred"
    }
    regime = regime_data.get("regime", "RANGING")
    comp   = regime_data.get("composite", 0)
    ax.barh(["Composite Score"], [comp],
            color=regime_colors.get(regime, "orange"))
    ax.axvline(0, color="black", linewidth=1)
    ax.set_xlim(-5, 5)
    ax.set_title(f"Market Regime: {regime}")
    metrics_text = (
        f"ADX: {regime_data.get('adx', 0):.1f}\n"
        f"VIX: {regime_data.get('vix', 0):.1f}\n"
        f"News: {regime_data.get('news_score', 0):+.3f}"
    )
    ax.text(0.02, 0.5, metrics_text, transform=ax.transAxes,
            fontsize=9, verticalalignment="center")

    # ── 6. Strategy frequency ─────────────────────────────────────────────
    ax = axes[1, 2]
    all_strats = []
    for s in df["strategies"]:
        all_strats.extend([x.strip() for x in s.split(",")])
    strat_counts = pd.Series(all_strats).value_counts()
    strat_counts.plot(kind="bar", ax=ax, color="purple", alpha=0.7)
    ax.set_title("Strategy Frequency")
    ax.set_ylabel("Count")
    ax.tick_params(axis="x", rotation=30)

    plt.tight_layout()
    plt.savefig("/tmp/dashboard.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Dashboard saved to /tmp/dashboard.png")


def save_to_drive(trades: list, backtest_df: pd.DataFrame = None):
    """Save scan results and backtest to Google Drive as CSV + Excel."""
    try:
        from google.colab import drive
        drive.mount("/content/drive", force_remount=False)
        path = CONFIG["DRIVE_OUTPUT_PATH"]
        os.makedirs(path, exist_ok=True)

        date_str = datetime.now().strftime("%Y%m%d_%H%M")

        # ── Trade signals CSV ─────────────────────────────────────────────
        if trades:
            trades_df = pd.DataFrame(trades).drop(columns=["portfolio"], errors="ignore")
            csv_path  = f"{path}signals_{date_str}.csv"
            trades_df.to_csv(csv_path, index=False)
            print(f"✅ Signals saved: {csv_path}")

            # Excel with formatting
            excel_path = f"{path}signals_{date_str}.xlsx"
            with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
                trades_df.to_excel(writer, sheet_name="Signals", index=False)
                if backtest_df is not None and not backtest_df.empty:
                    backtest_df.to_excel(writer, sheet_name="Backtest", index=False)
            print(f"✅ Excel saved: {excel_path}")

        # ── Dashboard image ───────────────────────────────────────────────
        if os.path.exists("/tmp/dashboard.png"):
            import shutil
            img_path = f"{path}dashboard_{date_str}.png"
            shutil.copy("/tmp/dashboard.png", img_path)
            print(f"✅ Dashboard saved: {img_path}")

    except Exception as e:
        log.error(f"Drive save failed: {e}")
        print("Could not save to Drive. Check Drive is mounted and path is correct.")

# MAIN EXECUTION BLOCK
# Run this cell last after all cells above are executed.
# ===========================================================================
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

if __name__ == "__main__":

    print("\n" + "="*60)
    print("  MASTER SWING TRADING SYSTEM — STARTING")
    print("="*60)

    # ── Step 1: Load FinBERT ───────────────────────────────────────────────
    print("\n[1/5] Loading FinBERT model...")
    load_finbert()

    # ── Step 2: Detect Market Regime ──────────────────────────────────────
    print("\n[2/5] Detecting market regime...")
    regime_data = detect_market_regime()

    # ── Step 3: Run Scanner ───────────────────────────────────────────────
    print("\n[3/5] Running full market scan...")
    trades = run_scan(top_n=20)

    # ── Step 4: Plot Dashboard ────────────────────────────────────────────
    print("\n[4/5] Generating dashboard...")
    plot_dashboard(trades, regime_data)

    # ── Step 5: Send Alerts ───────────────────────────────────────────────
    print("\n[5/5] Dispatching alerts...")
    dispatch_alerts(trades)

    # ── Optional: Backtest top signals ────────────────────────────────────
    # Uncomment to run backtesting (takes 5–15 minutes)
    #
    # print("\n[BONUS] Running backtest on top symbols...")
    # top_symbols = [t["symbol"] for t in trades[:30]]
    # bt_results  = backtest_universe(top_symbols, strategy="breakout")
    # save_to_drive(trades, bt_results)

    # ── Save without backtest (fast path) ─────────────────────────────────
    save_to_drive(trades)

    print("\n✅ All done. Check your Telegram/email for alerts.")
